ENEMIES = {
    "goblin": {
        "name": "Goblin",
        "hp": 50,
        "speed": 80,
        "armor": 0,
        "gold_reward": 10,
        "send_cost": 15,
        "send_count": 3,
        "flying": False,
        "color": (0, 200, 0),
        "radius": 8,
    },
    "orc": {
        "name": "Orc",
        "hp": 150,
        "speed": 40,
        "armor": 0,
        "gold_reward": 25,
        "send_cost": 30,
        "send_count": 1,
        "flying": False,
        "color": (160, 160, 0),
        "radius": 12,
    },
    "dark_knight": {
        "name": "Dark Knight",
        "hp": 250,
        "speed": 50,
        "armor": 5,
        "gold_reward": 40,
        "send_cost": 50,
        "send_count": 1,
        "flying": False,
        "color": (80, 80, 80),
        "radius": 11,
    },
    "dragon": {
        "name": "Dragon",
        "hp": 800,
        "speed": 60,
        "armor": 0,
        "gold_reward": 100,
        "send_cost": 120,
        "send_count": 1,
        "flying": True,
        "color": (220, 20, 20),
        "radius": 16,
    },
}

ENEMY_ORDER = ["goblin", "orc", "dark_knight", "dragon"]
