TOWERS = {
    "archer": {
        "name": "Archer Tower",
        "cost": 50,
        "damage": 15,
        "range": 120,
        "fire_rate": 1.0,       # shots per second
        "projectile_speed": 400,
        "upgrade_cost": 40,
        "upgrade_damage_bonus": 10,
        "upgrade_range_bonus": 10,
        "description": "Fast attacks, single target",
        "color": (0, 180, 0),
        "projectile_color": (180, 140, 60),
        "letter": "A",
        "can_hit_flying": True,
        "aoe_radius": 0,
        "dot_damage": 0,
        "dot_duration": 0,
        "slow_factor": 0,
        "slow_duration": 0,
    },
    "wizard": {
        "name": "Wizard Tower",
        "cost": 100,
        "damage": 25,
        "range": 100,
        "fire_rate": 0.6,
        "projectile_speed": 300,
        "upgrade_cost": 75,
        "upgrade_damage_bonus": 15,
        "upgrade_range_bonus": 8,
        "description": "AOE magic damage",
        "color": (130, 0, 220),
        "projectile_color": (180, 100, 255),
        "letter": "W",
        "can_hit_flying": True,
        "aoe_radius": 50,
        "dot_damage": 0,
        "dot_duration": 0,
        "slow_factor": 0,
        "slow_duration": 0,
    },
    "fire": {
        "name": "Fire Tower",
        "cost": 80,
        "damage": 8,
        "range": 90,
        "fire_rate": 0.8,
        "projectile_speed": 350,
        "upgrade_cost": 60,
        "upgrade_damage_bonus": 5,
        "upgrade_range_bonus": 8,
        "description": "Burns enemies over time",
        "color": (255, 80, 0),
        "projectile_color": (255, 160, 40),
        "letter": "F",
        "can_hit_flying": False,
        "aoe_radius": 0,
        "dot_damage": 5,
        "dot_duration": 3.0,
        "slow_factor": 0,
        "slow_duration": 0,
    },
    "ice": {
        "name": "Ice Tower",
        "cost": 70,
        "damage": 10,
        "range": 110,
        "fire_rate": 0.5,
        "projectile_speed": 250,
        "upgrade_cost": 50,
        "upgrade_damage_bonus": 5,
        "upgrade_range_bonus": 10,
        "description": "Slows enemies",
        "color": (0, 180, 255),
        "projectile_color": (150, 220, 255),
        "letter": "I",
        "can_hit_flying": False,
        "aoe_radius": 0,
        "dot_damage": 0,
        "dot_duration": 0,
        "slow_factor": 0.5,
        "slow_duration": 2.0,
    },
}

TOWER_ORDER = ["archer", "wizard", "fire", "ice"]
